//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_question_answers
    {
        public long id { get; set; }
        public long question { get; set; }
        public string answer { get; set; }
        public sbyte answerformat { get; set; }
        public decimal fraction { get; set; }
        public string feedback { get; set; }
        public sbyte feedbackformat { get; set; }
    }
}
