//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_message
    {
        public long id { get; set; }
        public long useridfrom { get; set; }
        public long useridto { get; set; }
        public string subject { get; set; }
        public string fullmessage { get; set; }
        public Nullable<short> fullmessageformat { get; set; }
        public string fullmessagehtml { get; set; }
        public string smallmessage { get; set; }
        public Nullable<bool> notification { get; set; }
        public string contexturl { get; set; }
        public string contexturlname { get; set; }
        public long timecreated { get; set; }
    }
}
