//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_HocKy
    {
        public MOD_HocKy()
        {
            this.MOD_HocKy_ChuyenNganh = new HashSet<MOD_HocKy_ChuyenNganh>();
        }
    
        public int ID_moodle { get; set; }
        public int Ky_dang_ky { get; set; }
    
        public virtual ICollection<MOD_HocKy_ChuyenNganh> MOD_HocKy_ChuyenNganh { get; set; }
    }
}
