//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_HocVi
    {
        public int ID_hoc_vi { get; set; }
        public string Ma_hoc_vi { get; set; }
        public string Hoc_vi { get; set; }
    }
}
