//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ChuongTrinhDaoTao
    {
        public int ID_dt { get; set; }
        public int ID_he { get; set; }
        public int ID_khoa { get; set; }
        public int Khoa_hoc { get; set; }
        public int ID_chuyen_nganh { get; set; }
        public float So_hoc_trinh { get; set; }
        public int So_ky_hoc { get; set; }
        public Nullable<int> So { get; set; }
    }
}
