//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_SukiensTinChi_TC
    {
        public int ID { get; set; }
        public int ID_lop_tc { get; set; }
        public int ID_phong { get; set; }
        public int ID_cb { get; set; }
        public int Ca_hoc { get; set; }
        public int Thu { get; set; }
        public int Tiet { get; set; }
        public int So_tiet { get; set; }
        public int Loai_tiet { get; set; }
        public bool Da_xep_lich { get; set; }
    }
}
