//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_GiaoVienMonDay
    {
        public int ID_cb { get; set; }
        public int ID_mon { get; set; }
        public int ID_bm { get; set; }
    }
}
