//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class POR_LopTC_TaiLieu
    {
        public Nullable<int> ID_lop_tc { get; set; }
        public Nullable<int> ID_tl { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
        public Nullable<int> ID_cb { get; set; }
        public int ID { get; set; }
    
        public virtual PLAN_GiaoVien PLAN_GiaoVien { get; set; }
        public virtual POR_TaiLieu POR_TaiLieu { get; set; }
        public virtual PLAN_LopTinChi_TC PLAN_LopTinChi_TC { get; set; }
    }
}
