//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class POR_GiaoVien
    {
        public int ID_cb { get; set; }
        public string Mat_khau { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Trang_thai { get; set; }
    
        public virtual PLAN_GiaoVien PLAN_GiaoVien { get; set; }
    }
}
