//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLopTC
    {
        public int ID_lop_tc { get; set; }
        public int ID_mon { get; set; }
        public string Ten_mon { get; set; }
        public string Ky_hieu_lop_tc { get; set; }
        public int Ky_dang_ky { get; set; }
        public int Dot { get; set; }
        public int Hoc_ky { get; set; }
        public string Nam_hoc { get; set; }
        public string Ma_nhom { get; set; }
        public System.DateTime Tu_ngay { get; set; }
        public System.DateTime Den_ngay { get; set; }
    }
}
