//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MARK_MonHoc> MARK_MonHoc { get; set; }
        public DbSet<PLAN_LopTinChi_TC> PLAN_LopTinChi_TC { get; set; }
        public DbSet<PLAN_MonTinChi_TC> PLAN_MonTinChi_TC { get; set; }
        public DbSet<PLAN_SukiensTinChi_TC> PLAN_SukiensTinChi_TC { get; set; }
        public DbSet<STU_HoSoSinhVien> STU_HoSoSinhVien { get; set; }
        public DbSet<STU_DanhSach> STU_DanhSach { get; set; }
        public DbSet<ViewNamHoc> ViewNamHoc { get; set; }
        public DbSet<PLAN_HocKyDangKy_TC> PLAN_HocKyDangKy_TC { get; set; }
        public DbSet<PLAN_ChuongTrinhDaoTao> PLAN_ChuongTrinhDaoTao { get; set; }
        public DbSet<PLAN_ChuongTrinhDaoTaoChiTiet> PLAN_ChuongTrinhDaoTaoChiTiet { get; set; }
        public DbSet<STU_ChuyenNganh> STU_ChuyenNganh { get; set; }
        public DbSet<STU_He> STU_He { get; set; }
        public DbSet<STU_Khoa> STU_Khoa { get; set; }
        public DbSet<STU_Nganh> STU_Nganh { get; set; }
        public DbSet<ViewLopTC> ViewLopTC { get; set; }
        public DbSet<STU_Lop> STU_Lop { get; set; }
    }
}
