//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_user
    {
        public long id { get; set; }
        public string auth { get; set; }
        public bool confirmed { get; set; }
        public bool policyagreed { get; set; }
        public bool deleted { get; set; }
        public bool suspended { get; set; }
        public long mnethostid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string idnumber { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public bool emailstop { get; set; }
        public string icq { get; set; }
        public string skype { get; set; }
        public string yahoo { get; set; }
        public string aim { get; set; }
        public string msn { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string institution { get; set; }
        public string department { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string lang { get; set; }
        public string theme { get; set; }
        public string timezone { get; set; }
        public long firstaccess { get; set; }
        public long lastaccess { get; set; }
        public long lastlogin { get; set; }
        public long currentlogin { get; set; }
        public string lastip { get; set; }
        public string secret { get; set; }
        public long picture { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public sbyte descriptionformat { get; set; }
        public bool mailformat { get; set; }
        public bool maildigest { get; set; }
        public sbyte maildisplay { get; set; }
        public bool htmleditor { get; set; }
        public bool autosubscribe { get; set; }
        public bool trackforums { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public long trustbitmask { get; set; }
        public string imagealt { get; set; }
        public bool screenreader { get; set; }
    }
}
