//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_question
    {
        public long id { get; set; }
        public long category { get; set; }
        public long parent { get; set; }
        public string name { get; set; }
        public string questiontext { get; set; }
        public sbyte questiontextformat { get; set; }
        public string generalfeedback { get; set; }
        public sbyte generalfeedbackformat { get; set; }
        public decimal defaultmark { get; set; }
        public decimal penalty { get; set; }
        public string qtype { get; set; }
        public long length { get; set; }
        public string stamp { get; set; }
        public string version { get; set; }
        public bool hidden { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<long> modifiedby { get; set; }
    }
}
