//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_files_reference
    {
        public long id { get; set; }
        public long repositoryid { get; set; }
        public Nullable<long> lastsync { get; set; }
        public Nullable<long> lifetime { get; set; }
        public string reference { get; set; }
        public string referencehash { get; set; }
    }
}
