//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_course
    {
        public long id { get; set; }
        public long category { get; set; }
        public long sortorder { get; set; }
        public string fullname { get; set; }
        public string shortname { get; set; }
        public string idnumber { get; set; }
        public string summary { get; set; }
        public sbyte summaryformat { get; set; }
        public string format { get; set; }
        public sbyte showgrades { get; set; }
        public string sectioncache { get; set; }
        public string modinfo { get; set; }
        public int newsitems { get; set; }
        public long startdate { get; set; }
        public int numsections { get; set; }
        public long marker { get; set; }
        public long maxbytes { get; set; }
        public short legacyfiles { get; set; }
        public short showreports { get; set; }
        public bool visible { get; set; }
        public bool visibleold { get; set; }
        public sbyte hiddensections { get; set; }
        public short groupmode { get; set; }
        public short groupmodeforce { get; set; }
        public long defaultgroupingid { get; set; }
        public string lang { get; set; }
        public string theme { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public bool requested { get; set; }
        public bool enablecompletion { get; set; }
        public bool completionstartonenrol { get; set; }
        public bool completionnotify { get; set; }
        public sbyte coursedisplay { get; set; }
    }
}
