//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_quiz_question_response_stats
    {
        public long id { get; set; }
        public long quizstatisticsid { get; set; }
        public long questionid { get; set; }
        public string subqid { get; set; }
        public string aid { get; set; }
        public string response { get; set; }
        public Nullable<long> rcount { get; set; }
        public decimal credit { get; set; }
    }
}
