//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_user_info_data
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long fieldid { get; set; }
        public string data { get; set; }
        public sbyte dataformat { get; set; }
    }
}
