//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_user_info_field
    {
        public long id { get; set; }
        public string shortname { get; set; }
        public string name { get; set; }
        public string datatype { get; set; }
        public string description { get; set; }
        public sbyte descriptionformat { get; set; }
        public long categoryid { get; set; }
        public long sortorder { get; set; }
        public sbyte required { get; set; }
        public sbyte locked { get; set; }
        public short visible { get; set; }
        public sbyte forceunique { get; set; }
        public sbyte signup { get; set; }
        public string defaultdata { get; set; }
        public sbyte defaultdataformat { get; set; }
        public string param1 { get; set; }
        public string param2 { get; set; }
        public string param3 { get; set; }
        public string param4 { get; set; }
        public string param5 { get; set; }
    }
}
