//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_context
    {
        public long id { get; set; }
        public long contextlevel { get; set; }
        public long instanceid { get; set; }
        public string path { get; set; }
        public sbyte depth { get; set; }
    }
}
