//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_grading_instances
    {
        public long id { get; set; }
        public long definitionid { get; set; }
        public long raterid { get; set; }
        public Nullable<long> itemid { get; set; }
        public Nullable<decimal> rawgrade { get; set; }
        public long status { get; set; }
        public string feedback { get; set; }
        public Nullable<sbyte> feedbackformat { get; set; }
        public long timemodified { get; set; }
    }
}
