//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit_external_services
    {
        public long id { get; set; }
        public string name { get; set; }
        public bool enabled { get; set; }
        public string requiredcapability { get; set; }
        public bool restrictedusers { get; set; }
        public string component { get; set; }
        public long timecreated { get; set; }
        public Nullable<long> timemodified { get; set; }
        public string shortname { get; set; }
        public bool downloadfiles { get; set; }
    }
}
