//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongThongTinSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_NguoiDung
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string FullName { get; set; }
        public int UserGroup { get; set; }
        public int Active { get; set; }
        public int ID_phong { get; set; }
        public int ID_khoa { get; set; }
        public int ID_Bomon { get; set; }
        public string May_tram { get; set; }
        public string UserNameLDAP { get; set; }
        public string adsPathLDAP { get; set; }
        public string Email { get; set; }
        public string Dien_thoai { get; set; }
        public string MAC { get; set; }
    }
}
